# Generated by Django 3.2.14 on 2022-09-07 10:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_list_listy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='date',
            field=models.DateField(blank=True, default=datetime.date.today, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='author',
            name='depart',
            field=models.CharField(max_length=50, verbose_name='Департамент'),
        ),
        migrations.AlterField(
            model_name='author',
            name='surname',
            field=models.CharField(max_length=50, verbose_name='Фамилия'),
        ),
    ]
