# Generated by Django 3.2.14 on 2022-10-05 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20220907_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='depart',
            field=models.CharField(choices=[('МСК СКЛАД', 'МСК СКЛАД'), ('МСК ОФИС', 'МСК ОФИС'), ('ПРОИЗВОДСТВО', 'ПРОИЗВОДСТВО'), ('СКЛАД', 'СКЛАД'), ('ОФИС', 'ОФИС'), ('БУХГАЛТЕРИЯ', 'БУХГАЛТЕРИЯ')], max_length=50, verbose_name='Департамент'),
        ),
        migrations.AlterField(
            model_name='listy',
            name='numbers',
            field=models.PositiveIntegerField(default=1, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='listy',
            name='title',
            field=models.CharField(choices=[('TK-3160', 'TK-3160'), ('TK-1200', 'TK-1200'), ('TK-3100', 'TK-3100'), ('TK-1110', 'TK-1110'), ('TK-2335', 'TK-2335')], max_length=50, verbose_name='Картридж'),
        ),
    ]
