# Generated by Django 3.2.14 on 2022-10-05 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20221005_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listy',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Картридж'),
        ),
    ]
