# Generated by Django 3.2.14 on 2022-10-10 08:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_listy_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='date',
        ),
        migrations.AddField(
            model_name='listy',
            name='date',
            field=models.DateField(blank=True, default=datetime.date.today, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='author',
            name='depart',
            field=models.CharField(choices=[('МСК СКЛАД', 'МСК СКЛАД'), ('МСК ОФИС', 'МСК ОФИС'), ('ПРОИЗВОДСТВО', 'ПРОИЗВОДСТВО'), ('СКЛАД', 'СКЛАД'), ('ОФИС', 'ОФИС'), ('БУХГАЛТЕРИЯ', 'БУХГАЛТЕРИЯ'), ('SVETON', 'SVETON'), ('ЭЛЕКТРОПРОЕКТ', 'ЭЛЕКТРОПРОЕКТ')], max_length=50, verbose_name='Департамент'),
        ),
    ]
