# Generated by Django 3.2.14 on 2022-10-10 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20221010_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='depart',
            field=models.CharField(choices=[('МСК СКЛАД', 'МСК СКЛАД'), ('МСК ОФИС', 'МСК ОФИС'), ('ПРОИЗВОДСТВО', 'ПРОИЗВОДСТВО'), ('СКЛАД', 'СКЛАД'), ('ОФИС', 'ОФИС'), ('БУХГАЛТЕРИЯ', 'БУХГАЛТЕРИЯ'), ('СВЕТОН', 'СВЕТОН'), ('ЭЛЕКТРОПРОЕКТ', 'ЭЛЕКТРОПРОЕКТ'), ('МАГАЗИН БЕЛОВОДСКИЙ', 'МАГАЗИН БЕЛОВОДСКИЙ')], max_length=50, verbose_name='Департамент'),
        ),
    ]
